name: CI/CD

on:
  # Build + Deploy
  push:
    branches:
      - develop

jobs:
  deploy:
    name: 'Build and deploy'
    runs-on: ubuntu-latest
    steps:
      - name: Get repo
        uses: actions/checkout@v3

      - name: Push to registry
        run: |
          export CR_PAT=${{ secrets.GITHUB_TOKEN }}
          echo $CR_PAT | docker login ghcr.io -u Osbornnnnn --password-stdin
          docker push ghcr.io/Osbornnnnn/frontend:latest
