name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: "Deploy to staging"
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/key
          chmod 600 ~/.ssh/key
          cat >>~/.ssh/config <<END
          Host qq
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: deployer
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}

      - uses: actions/checkout@v2

      - name: Update frontend
        run: ls -LR

      - name: Deploy frontend
        run: ssh qq 'cd /home/deployer/vsau'
