name: Deploy

on:
  # Tests + Deploy
  push:
    branches:
      - main
      - develop

  # Tests
  # pull_request:
  #   branches:
  #     - main

jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/key
          chmod 600 ~/.ssh/key
          cat >>~/.ssh/config <<END
          Host qq
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: deployer
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}

      - name: Get frontend repo
        uses: actions/checkout@v2

      - name: Update frontend
        run: rsync -e 'ssh -i ~/.ssh/key -o StrictHostKeyChecking=no' --archive --compress --delete ./app deployer@${{ secrets.SSH_HOST }}:/home/deployer/vsau/frontend/

      - name: Deploy frontend
        run: ssh qq 'cd /home/deployer/vsau'
